// ── Is the watch-list still the example one? ──────────────────────────────────
//
// scanner/portals.yml ships with the maintainer's ~38-company example list. A
// user who skips onboarding's companies step (or never finds it) keeps scanning
// that list and gets digests full of roles at companies they never chose. That
// is a silent, confusing failure, so both the scanner and the dashboard need to
// be able to answer one question: "is this file still the example list?"
//
// DETECTION CHOICE — marker, not hash.
// A byte-hash of the shipped file was the other option. It was rejected because
// it goes stale two ways: it breaks the moment the example list is edited
// upstream (every user then gets told they're personalized when they aren't),
// and it also breaks when a user tunes a single keyword by hand (they get told
// they're on the example list forever). Both failures are silent.
//
// Instead we look for the fingerprints that JobBud's own generator leaves behind
// (api/coach.js buildPortalsYml), either of which means "a human chose this list":
//   1. the "Generated by JobBud onboarding" line in the header comment, and
//   2. `category: user`, which the generator stamps on every entry it writes.
// Two independent signals, so hand-editing the header away doesn't resurrect the
// nudge. The example list has neither.
//
// Known limit, and it is deliberate: someone who hand-edits scanner/portals.yml
// in place — replacing the example companies without going through onboarding or
// the dashboard's Watch List editor — still looks like the example list. The
// nudge they see points at the editor, and one save from there clears it for
// good. We prefer that over a false "you're all set" for someone who really is
// scanning the maintainer's companies.

export const PORTALS_GENERATED_MARKER = 'Generated by JobBud onboarding';

// True when portals.yml carries neither generator fingerprint. An empty or
// missing file is NOT the example list — there is nothing to warn about, and a
// failed read should never produce a scary line in someone's digest.
export function isStarterPortalsList(yamlText) {
  if (typeof yamlText !== 'string' || !yamlText.trim()) return false;
  if (yamlText.includes(PORTALS_GENERATED_MARKER)) return false;
  if (/^\s*category:\s*["']?user["']?\s*$/m.test(yamlText)) return false;
  return true;
}

// One plain-English line, shared by the scanner log and the digest so the wording
// never drifts between them.
export const STARTER_LIST_NOTICE =
  "Heads up: you're scanning the example company list — set your own in the dashboard's Watch List.";
